"""Initial migration.

Revision ID: ab15506a6f85
Revises: 03d6d8a91f0d
Create Date: 2020-04-07 15:46:02.381397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab15506a6f85'
down_revision = '03d6d8a91f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mhs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('kelas', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alamat'),
    sa.UniqueConstraint('kelas'),
    sa.UniqueConstraint('nama'),
    sa.UniqueConstraint('nim')
    )
    op.drop_index('nim', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('kelas', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nama', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nim', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('nim', 'user', ['nim'], unique=True)
    op.drop_table('mhs')
    # ### end Alembic commands ###
