"""Initial migration.

Revision ID: c89472cba1f5
Revises: ab15506a6f85
Create Date: 2020-04-07 15:48:50.222038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89472cba1f5'
down_revision = 'ab15506a6f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('alamat', table_name='mhs')
    op.drop_index('kelas', table_name='mhs')
    op.drop_index('nama', table_name='mhs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nama', 'mhs', ['nama'], unique=True)
    op.create_index('kelas', 'mhs', ['kelas'], unique=True)
    op.create_index('alamat', 'mhs', ['alamat'], unique=True)
    # ### end Alembic commands ###
