"""Initial migration.

Revision ID: e5638e55e8f8
Revises: aab60456f86f
Create Date: 2020-04-07 15:39:06.817559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5638e55e8f8'
down_revision = 'aab60456f86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alamat', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('kelas', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('nama', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('nim', sa.String(length=10), nullable=True))
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['nama'])
    op.create_unique_constraint(None, 'user', ['alamat'])
    op.create_unique_constraint(None, 'user', ['kelas'])
    op.create_unique_constraint(None, 'user', ['nim'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'nim')
    op.drop_column('user', 'nama')
    op.drop_column('user', 'kelas')
    op.drop_column('user', 'alamat')
    # ### end Alembic commands ###
